apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: mynk11/brewapps:v1
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGODB_URI

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-srv
spec:
  type: NodePort
  selector:
    app: bookstore
  ports:
    - name: bookstore
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
